import "~/styles/globals.css";

import type { Metadata } from "next";
import Link from "next/link";
import { Geist } from "next/font/google";
import {
  ConvexClientProvider,
  PostHogProvider,
  ThemeProvider,
} from "~/app/providers";
import { ThemeToggle } from "~/app/theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} antialiased`}>
        <ConvexClientProvider>
          <PostHogProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              <main className="container mx-auto p-4">{children}</main>
              <Footer />
            </ThemeProvider>
          </PostHogProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className="container mx-auto flex items-center justify-between p-4">
      <Link href="/" className="text-2xl">
        MediaNerdle
      </Link>
      <div>
        <ThemeToggle />
      </div>
    </header>
  );
}

function Footer() {
  return <footer></footer>;
}
